# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Block_Diagram_UART/Block_Diagram_UART.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART || ORIG_REF_NAME==Block_Diagram_UART} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_0/Block_Diagram_UART_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_microblaze_0_0 || ORIG_REF_NAME==Block_Diagram_UART_microblaze_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_dlmb_v10_0/Block_Diagram_UART_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_dlmb_v10_0 || ORIG_REF_NAME==Block_Diagram_UART_dlmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_ilmb_v10_0/Block_Diagram_UART_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_ilmb_v10_0 || ORIG_REF_NAME==Block_Diagram_UART_ilmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_dlmb_bram_if_cntlr_0/Block_Diagram_UART_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_UART_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_ilmb_bram_if_cntlr_0/Block_Diagram_UART_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_UART_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_lmb_bram_0/Block_Diagram_UART_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_lmb_bram_0 || ORIG_REF_NAME==Block_Diagram_UART_lmb_bram_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_axi_intc_0/Block_Diagram_UART_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Block_Diagram_UART_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_xlconcat_0/Block_Diagram_UART_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Block_Diagram_UART_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_mdm_1_0/Block_Diagram_UART_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_mdm_1_0 || ORIG_REF_NAME==Block_Diagram_UART_mdm_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_clk_wiz_1_0/Block_Diagram_UART_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_clk_wiz_1_0 || ORIG_REF_NAME==Block_Diagram_UART_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_rst_clk_wiz_1_100M_0/Block_Diagram_UART_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_Diagram_UART_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_util_vector_logic_0_0/Block_Diagram_UART_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_util_vector_logic_0_0 || ORIG_REF_NAME==Block_Diagram_UART_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/Block_Diagram_UART_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_smartconnect_0_0 || ORIG_REF_NAME==Block_Diagram_UART_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/bd_cb54.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_0/bd_cb54_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_1/bd_cb54_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_2/bd_cb54_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_3/bd_cb54_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_4/bd_cb54_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_5/bd_cb54_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_6/bd_cb54_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_7/bd_cb54_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_8/bd_cb54_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_9/bd_cb54_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_10/bd_cb54_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_11/bd_cb54_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_12/bd_cb54_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_13/bd_cb54_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_14/bd_cb54_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_15/bd_cb54_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_16/bd_cb54_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_17/bd_cb54_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_18/bd_cb54_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_19/bd_cb54_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_20/bd_cb54_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_21/bd_cb54_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_22/bd_cb54_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_23/bd_cb54_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_24/bd_cb54_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_25/bd_cb54_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_26/bd_cb54_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_27/bd_cb54_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_28/bd_cb54_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_29/bd_cb54_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_30/bd_cb54_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_31/bd_cb54_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_32/bd_cb54_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_33/bd_cb54_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_34/bd_cb54_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_35/bd_cb54_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_36/bd_cb54_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_37/bd_cb54_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_38/bd_cb54_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_39/bd_cb54_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_40/bd_cb54_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_41/bd_cb54_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_42/bd_cb54_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_43/bd_cb54_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_44/bd_cb54_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_45/bd_cb54_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_46/bd_cb54_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_47/bd_cb54_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_48/bd_cb54_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_49/bd_cb54_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_50/bd_cb54_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_51/bd_cb54_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_52/bd_cb54_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_53/bd_cb54_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_gpio_0_0/Block_Diagram_UART_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_UART_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_timer_0_0/Block_Diagram_UART_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_axi_timer_0_0 || ORIG_REF_NAME==Block_Diagram_UART_axi_timer_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_xlconstant_1_0/Block_Diagram_UART_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_xlconstant_1_0 || ORIG_REF_NAME==Block_Diagram_UART_xlconstant_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_mig_7series_0_0/Block_Diagram_UART_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_mig_7series_0_0 || ORIG_REF_NAME==Block_Diagram_UART_mig_7series_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_xlconcat_0_1/Block_Diagram_UART_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_xlconcat_0_1 || ORIG_REF_NAME==Block_Diagram_UART_xlconcat_0_1} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_util_vector_logic_1_0/Block_Diagram_UART_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_util_vector_logic_1_0 || ORIG_REF_NAME==Block_Diagram_UART_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_UART/ip/Block_Diagram_UART_ila_0_0/Block_Diagram_UART_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_ila_0_0 || ORIG_REF_NAME==Block_Diagram_UART_ila_0_0} -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_0/Block_Diagram_UART_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_microblaze_0_0 || ORIG_REF_NAME==Block_Diagram_UART_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_0/Block_Diagram_UART_microblaze_0_0_ooc_debug.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_lmb_bram_0/Block_Diagram_UART_lmb_bram_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_axi_intc_0/Block_Diagram_UART_microblaze_0_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Block_Diagram_UART_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_axi_intc_0/Block_Diagram_UART_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Block_Diagram_UART_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_microblaze_0_axi_intc_0/Block_Diagram_UART_microblaze_0_axi_intc_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_mdm_1_0/Block_Diagram_UART_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_mdm_1_0 || ORIG_REF_NAME==Block_Diagram_UART_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_mdm_1_0/Block_Diagram_UART_mdm_1_0_ooc_trace.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_clk_wiz_1_0/Block_Diagram_UART_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_clk_wiz_1_0 || ORIG_REF_NAME==Block_Diagram_UART_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_clk_wiz_1_0/Block_Diagram_UART_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_clk_wiz_1_0 || ORIG_REF_NAME==Block_Diagram_UART_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_clk_wiz_1_0/Block_Diagram_UART_clk_wiz_1_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_rst_clk_wiz_1_100M_0/Block_Diagram_UART_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_Diagram_UART_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_rst_clk_wiz_1_100M_0/Block_Diagram_UART_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_Diagram_UART_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_1/bd_cb54_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_1/bd_cb54_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_2/bd_cb54_arinsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_3/bd_cb54_rinsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_4/bd_cb54_awinsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_5/bd_cb54_winsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_6/bd_cb54_binsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_7/bd_cb54_aroutsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_8/bd_cb54_routsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_9/bd_cb54_awoutsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_10/bd_cb54_woutsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_11/bd_cb54_boutsw_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_12/bd_cb54_arni_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_13/bd_cb54_rni_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_14/bd_cb54_awni_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_15/bd_cb54_wni_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_16/bd_cb54_bni_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_20/bd_cb54_s00a2s_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_21/bd_cb54_sarn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_22/bd_cb54_srn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_23/bd_cb54_sawn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_24/bd_cb54_swn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_25/bd_cb54_sbn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_26/bd_cb54_m00s2a_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_27/bd_cb54_m00arn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_28/bd_cb54_m00rn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_29/bd_cb54_m00awn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_30/bd_cb54_m00wn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_31/bd_cb54_m00bn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_33/bd_cb54_m01s2a_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_34/bd_cb54_m01arn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_35/bd_cb54_m01rn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_36/bd_cb54_m01awn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_37/bd_cb54_m01wn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_38/bd_cb54_m01bn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_40/bd_cb54_m02s2a_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_41/bd_cb54_m02arn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_42/bd_cb54_m02rn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_43/bd_cb54_m02awn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_44/bd_cb54_m02wn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_45/bd_cb54_m02bn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_47/bd_cb54_m03s2a_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_48/bd_cb54_m03arn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_49/bd_cb54_m03rn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_50/bd_cb54_m03awn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_51/bd_cb54_m03wn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/bd_0/ip/ip_52/bd_cb54_m03bn_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_smartconnect_0_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_smartconnect_0_0 || ORIG_REF_NAME==Block_Diagram_UART_smartconnect_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_gpio_0_0/Block_Diagram_UART_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_UART_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_gpio_0_0/Block_Diagram_UART_axi_gpio_0_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_gpio_0_0/Block_Diagram_UART_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_UART_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_timer_0_0/Block_Diagram_UART_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_axi_timer_0_0 || ORIG_REF_NAME==Block_Diagram_UART_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_axi_timer_0_0/Block_Diagram_UART_axi_timer_0_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_mig_7series_0_0/Block_Diagram_UART_mig_7series_0_0/user_design/constraints/Block_Diagram_UART_mig_7series_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_mig_7series_0_0 || ORIG_REF_NAME==Block_Diagram_UART_mig_7series_0_0} -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_mig_7series_0_0/Block_Diagram_UART_mig_7series_0_0/user_design/constraints/Block_Diagram_UART_mig_7series_0_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_ila_0_0 || ORIG_REF_NAME==Block_Diagram_UART_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Block_Diagram_UART_ila_0_0 || ORIG_REF_NAME==Block_Diagram_UART_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/ip/Block_Diagram_UART_ila_0_0/Block_Diagram_UART_ila_0_0_ooc.xdc

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_UART/Acquire_UART.gen/sources_1/bd/Block_Diagram_UART/Block_Diagram_UART_ooc.xdc
