# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.srcs/sources_1/bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0.xci
# IP: The module: 'Block_Diagram_DDR3_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.gen/sources_1/bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_DDR3_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.gen/sources_1/bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_DDR3_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.srcs/sources_1/bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0.xci
# IP: The module: 'Block_Diagram_DDR3_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.gen/sources_1/bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_DDR3_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.gen/sources_1/bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_DDR3_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
