# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Block_Diagram_LCD/Block_Diagram_LCD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD || ORIG_REF_NAME==Block_Diagram_LCD} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_microblaze_0_0/Block_Diagram_LCD_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_microblaze_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_microblaze_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_dlmb_v10_0/Block_Diagram_LCD_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_dlmb_v10_0 || ORIG_REF_NAME==Block_Diagram_LCD_dlmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_ilmb_v10_0/Block_Diagram_LCD_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_ilmb_v10_0 || ORIG_REF_NAME==Block_Diagram_LCD_ilmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_dlmb_bram_if_cntlr_0/Block_Diagram_LCD_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_LCD_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_ilmb_bram_if_cntlr_0/Block_Diagram_LCD_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_LCD_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_lmb_bram_0/Block_Diagram_LCD_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_lmb_bram_0 || ORIG_REF_NAME==Block_Diagram_LCD_lmb_bram_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_mdm_1_0/Block_Diagram_LCD_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_mdm_1_0 || ORIG_REF_NAME==Block_Diagram_LCD_mdm_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_clk_wiz_1_0/Block_Diagram_LCD_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_clk_wiz_1_0 || ORIG_REF_NAME==Block_Diagram_LCD_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_rst_clk_wiz_1_100M_0/Block_Diagram_LCD_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_Diagram_LCD_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_mig_7series_0_0/Block_Diagram_LCD_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_mig_7series_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_mig_7series_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_smartconnect_0_0/Block_Diagram_LCD_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_smartconnect_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_smartconnect_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_axi_gpio_0_0/Block_Diagram_LCD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_axi_timer_0_0/Block_Diagram_LCD_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_axi_timer_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_axi_timer_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_xlconcat_0_0/Block_Diagram_LCD_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_xlconcat_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_xlconcat_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_axi_uartlite_0_0/Block_Diagram_LCD_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_axi_uartlite_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_axi_quad_spi_0_0/Block_Diagram_LCD_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_axi_quad_spi_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_xlconcat_1_0/Block_Diagram_LCD_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_xlconcat_1_0 || ORIG_REF_NAME==Block_Diagram_LCD_xlconcat_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_axi_intc_0_0/Block_Diagram_LCD_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_axi_intc_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_axi_intc_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_util_vector_logic_0_0/Block_Diagram_LCD_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_util_vector_logic_0_0 || ORIG_REF_NAME==Block_Diagram_LCD_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_LCD/ip/Block_Diagram_LCD_util_vector_logic_1_0/Block_Diagram_LCD_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_LCD_util_vector_logic_1_0 || ORIG_REF_NAME==Block_Diagram_LCD_util_vector_logic_1_0} -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_LCD/Acquire_LCD.gen/sources_1/bd/Block_Diagram_LCD/Block_Diagram_LCD_ooc.xdc
