domain_path: C:\IMR_Projects\IMR\Acquire_FPGA\Vitis_Workspace\MicroBlaze_uSD\MB_uSD_Platform\export\MB_uSD_Platform\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx_Embedded_2024.2\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
