# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Block_Diagram_DDR3/Block_Diagram_DDR3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3 || ORIG_REF_NAME==Block_Diagram_DDR3} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_microblaze_0_0/Block_Diagram_DDR3_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_microblaze_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_microblaze_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_dlmb_v10_0/Block_Diagram_DDR3_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_dlmb_v10_0 || ORIG_REF_NAME==Block_Diagram_DDR3_dlmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_ilmb_v10_0/Block_Diagram_DDR3_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_ilmb_v10_0 || ORIG_REF_NAME==Block_Diagram_DDR3_ilmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_dlmb_bram_if_cntlr_0/Block_Diagram_DDR3_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_DDR3_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_ilmb_bram_if_cntlr_0/Block_Diagram_DDR3_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_DDR3_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_lmb_bram_0/Block_Diagram_DDR3_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_lmb_bram_0 || ORIG_REF_NAME==Block_Diagram_DDR3_lmb_bram_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mdm_1_0/Block_Diagram_DDR3_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_mdm_1_0 || ORIG_REF_NAME==Block_Diagram_DDR3_mdm_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_rst_clk_wiz_1_100M_0/Block_Diagram_DDR3_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_Diagram_DDR3_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_util_vector_logic_0_0/Block_Diagram_DDR3_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_util_vector_logic_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_smartconnect_0_0/Block_Diagram_DDR3_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_smartconnect_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_smartconnect_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_mig_7series_0_0/Block_Diagram_DDR3_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_mig_7series_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_mig_7series_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_axi_gpio_0_0/Block_Diagram_DDR3_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_axi_timer_0_0/Block_Diagram_DDR3_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_axi_timer_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_axi_timer_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_axi_uartlite_0_0/Block_Diagram_DDR3_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_axi_uartlite_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_xlconcat_0_0/Block_Diagram_DDR3_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_xlconcat_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_xlconcat_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_axi_intc_0_0/Block_Diagram_DDR3_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_axi_intc_0_0 || ORIG_REF_NAME==Block_Diagram_DDR3_axi_intc_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_util_vector_logic_1_1/Block_Diagram_DDR3_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_util_vector_logic_1_1 || ORIG_REF_NAME==Block_Diagram_DDR3_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_xlconcat_1_0/Block_Diagram_DDR3_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_xlconcat_1_0 || ORIG_REF_NAME==Block_Diagram_DDR3_xlconcat_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_DDR3/ip/Block_Diagram_DDR3_clk_wiz_1_0/Block_Diagram_DDR3_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_DDR3_clk_wiz_1_0 || ORIG_REF_NAME==Block_Diagram_DDR3_clk_wiz_1_0} -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_DDR3/Acquire_DDR3.gen/sources_1/bd/Block_Diagram_DDR3/Block_Diagram_DDR3_ooc.xdc
