# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Block_Diagram_Timer/Block_Diagram_Timer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer || ORIG_REF_NAME==Block_Diagram_Timer} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_microblaze_0_2/Block_Diagram_Timer_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_microblaze_0_2 || ORIG_REF_NAME==Block_Diagram_Timer_microblaze_0_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_dlmb_v10_2/Block_Diagram_Timer_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_dlmb_v10_2 || ORIG_REF_NAME==Block_Diagram_Timer_dlmb_v10_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_ilmb_v10_2/Block_Diagram_Timer_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_ilmb_v10_2 || ORIG_REF_NAME==Block_Diagram_Timer_ilmb_v10_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_dlmb_bram_if_cntlr_2/Block_Diagram_Timer_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==Block_Diagram_Timer_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_ilmb_bram_if_cntlr_2/Block_Diagram_Timer_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==Block_Diagram_Timer_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_blk_mem_gen_0_0/Block_Diagram_Timer_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_blk_mem_gen_0_0 || ORIG_REF_NAME==Block_Diagram_Timer_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_mdm_1_0/Block_Diagram_Timer_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_mdm_1_0 || ORIG_REF_NAME==Block_Diagram_Timer_mdm_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_clk_wiz_1_2/Block_Diagram_Timer_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_clk_wiz_1_2 || ORIG_REF_NAME==Block_Diagram_Timer_clk_wiz_1_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_rst_clk_wiz_1_100M_2/Block_Diagram_Timer_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==Block_Diagram_Timer_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_util_vector_logic_0_1/Block_Diagram_Timer_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_util_vector_logic_0_1 || ORIG_REF_NAME==Block_Diagram_Timer_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_axi_gpio_0_0/Block_Diagram_Timer_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_Timer_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_smartconnect_0_0/Block_Diagram_Timer_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_smartconnect_0_0 || ORIG_REF_NAME==Block_Diagram_Timer_smartconnect_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_axi_timer_0_1/Block_Diagram_Timer_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_axi_timer_0_1 || ORIG_REF_NAME==Block_Diagram_Timer_axi_timer_0_1} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_axi_timer_1_0/Block_Diagram_Timer_axi_timer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_axi_timer_1_0 || ORIG_REF_NAME==Block_Diagram_Timer_axi_timer_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_axi_intc_0_1/Block_Diagram_Timer_axi_intc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_axi_intc_0_1 || ORIG_REF_NAME==Block_Diagram_Timer_axi_intc_0_1} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_xlconstant_0_0/Block_Diagram_Timer_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_xlconstant_0_0 || ORIG_REF_NAME==Block_Diagram_Timer_xlconstant_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_Timer/ip/Block_Diagram_Timer_xlconstant_1_0/Block_Diagram_Timer_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_Timer_xlconstant_1_0 || ORIG_REF_NAME==Block_Diagram_Timer_xlconstant_1_0} -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_Timer/Acquire_Timer.gen/sources_1/bd/Block_Diagram_Timer/Block_Diagram_Timer_ooc.xdc
