# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Block_Diagram_ADC/Block_Diagram_ADC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC || ORIG_REF_NAME==Block_Diagram_ADC} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_microblaze_0_0/Block_Diagram_ADC_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_microblaze_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_microblaze_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_dlmb_v10_0/Block_Diagram_ADC_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_dlmb_v10_0 || ORIG_REF_NAME==Block_Diagram_ADC_dlmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_ilmb_v10_0/Block_Diagram_ADC_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_ilmb_v10_0 || ORIG_REF_NAME==Block_Diagram_ADC_ilmb_v10_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_dlmb_bram_if_cntlr_0/Block_Diagram_ADC_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_ADC_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_ilmb_bram_if_cntlr_0/Block_Diagram_ADC_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Diagram_ADC_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_lmb_bram_0/Block_Diagram_ADC_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_lmb_bram_0 || ORIG_REF_NAME==Block_Diagram_ADC_lmb_bram_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_mdm_1_0/Block_Diagram_ADC_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_mdm_1_0 || ORIG_REF_NAME==Block_Diagram_ADC_mdm_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_clk_wiz_1_0/Block_Diagram_ADC_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_clk_wiz_1_0 || ORIG_REF_NAME==Block_Diagram_ADC_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_rst_clk_wiz_1_100M_0/Block_Diagram_ADC_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_Diagram_ADC_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_util_vector_logic_0_0/Block_Diagram_ADC_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_util_vector_logic_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_axi_intc_0_0/Block_Diagram_ADC_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_axi_intc_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_axi_intc_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_axi_timer_0_0/Block_Diagram_ADC_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_axi_timer_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_axi_timer_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_axi_gpio_0_0/Block_Diagram_ADC_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_axi_uartlite_0_0/Block_Diagram_ADC_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_axi_uartlite_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_smartconnect_0_0/Block_Diagram_ADC_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_smartconnect_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_smartconnect_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_xlconstant_0_0/Block_Diagram_ADC_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_xlconstant_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_xlconstant_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_xlconcat_0_0/Block_Diagram_ADC_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_xlconcat_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_xlconcat_0_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_xlconcat_1_0/Block_Diagram_ADC_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_xlconcat_1_0 || ORIG_REF_NAME==Block_Diagram_ADC_xlconcat_1_0} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_IMR_ADC_7476A_V1_0_0_7/Block_Diagram_ADC_IMR_ADC_7476A_V1_0_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_IMR_ADC_7476A_V1_0_0_7 || ORIG_REF_NAME==Block_Diagram_ADC_IMR_ADC_7476A_V1_0_0_7} -quiet] -quiet

# IP: bd/Block_Diagram_ADC/ip/Block_Diagram_ADC_xlslice_0_0/Block_Diagram_ADC_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ADC_xlslice_0_0 || ORIG_REF_NAME==Block_Diagram_ADC_xlslice_0_0} -quiet] -quiet

# XDC: c:/IMR_Projects/IMR/Acquire_FPGA/Vivado_Workspace/Acquire_ADC/Acquire_ADC.gen/sources_1/bd/Block_Diagram_ADC/Block_Diagram_ADC_ooc.xdc
